export const GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_SUCCESS =
  'GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_SUCCESS';
export const GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_REQUEST =
  'GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_REQUEST';
export const GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_FAILURE =
  'GOOGLE_AUTH_CLIENT_SUCCESS_SERVER_FAILURE';

export const JWT_AUTH_SUCCESS = 'JWT_AUTH_SUCCESS';
export const JWT_AUTH_REQUEST = 'JWT_AUTH_REQUEST';
export const JWT_AUTH_FAILURE = 'JWT_AUTH_FAILURE';

export const LOGOUT = 'LOGOUT';
