export const GET_ALL_POSTS_REQUESTS = 'GET_ALL_POSTS_REQUESTS';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR';

export const GET_POST_REQUESTS = 'GET_POST_REQUESTS';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const LIKE_POST_ERROR = 'LIKE_POST_ERROR';
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
